#8004表示注册到zookeeper服务器的支付服务提供者端口号
server:
  port: 7007


#服务别名----注册zookeeper到注册中心名称
spring:
  application:
    name: cloud-comsumer-order
  cloud:
    zookeeper:
      connect-string: 192.168.1.7:2181