server:
  port: 7008

spring:
  application:
    name: provide-consul-payment


  ####consul注册中心地址
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        hostname: 127.0.0.1
        service-name: provide-consul-payment-7008


