server:
  port: 7009

spring:
  application:
    name: comsumer-order-consul


  ####consul注册中心地址
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        hostname: 127.0.0.1
        service-name: comsumer-order-consul-7009